<a href="https://colab.research.google.com/github/ManishPrasad0511/SoME/blob/main/SoME_3d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
''' !sudo apt update
!sudo apt install libcairo2-dev ffmpeg \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython --upgrade '''

' !sudo apt update\n!sudo apt install libcairo2-dev ffmpeg     texlive texlive-latex-extra texlive-fonts-extra     texlive-latex-recommended texlive-science     tipa libpango1.0-dev\n!pip install manim\n!pip install IPython --upgrade '

In [ ]:
from manim import *
import numpy as np
import itertools

In [ ]:
a = 8
b = 6
c = 4
sides = [a,b,c]
N = 2
p1 = [-2,1,1]
p2 = [2,-2,-1]
d = 3

In [ ]:
signs  = list(itertools.product([1, -1], repeat=d))
final_pts = []
for i in signs:
  shifted_p2 = p2 + 2*(N-1)*np.multiply(i,sides)
  #print(shifted_p2)
  for j in range(d):
    final_shift = np.zeros(d)
    final_shift[j] = np.multiply(i,2*(sides[j]/2 - i[j]*(p2[j])))[j]
    #print(final_shift)
    final_pts.append(shifted_p2 + final_shift)
print(final_pts)
len(final_pts)

[array([22., 10.,  7.]), array([18., 20.,  7.]), array([18., 10., 13.]), array([22., 10., -9.]), array([18., 20., -9.]), array([ 18.,  10., -11.]), array([ 22., -14.,   7.]), array([ 18., -16.,   7.]), array([ 18., -14.,  13.]), array([ 22., -14.,  -9.]), array([ 18., -16.,  -9.]), array([ 18., -14., -11.]), array([-26.,  10.,   7.]), array([-14.,  20.,   7.]), array([-14.,  10.,  13.]), array([-26.,  10.,  -9.]), array([-14.,  20.,  -9.]), array([-14.,  10., -11.]), array([-26., -14.,   7.]), array([-14., -16.,   7.]), array([-14., -14.,  13.]), array([-26., -14.,  -9.]), array([-14., -16.,  -9.]), array([-14., -14., -11.])]


24

In [ ]:
final_coords_all = []

#for p in final_pts:
p = final_pts[0]

x_inters = abs(p[0])//(sides[0]/2) - abs(p[0])//sides[0]
y_inters = abs(p[1])//(sides[1]/2) - abs(p[1])//sides[1]
z_inters = abs(p[2])//(sides[2]/2) - abs(p[2])//sides[2]

x_walls = []
y_walls = []
z_walls = []
if p[0]>=0:
  x_start = sides[0]/2
else:
  x_start = -sides[0]/2
if p[1]>0:
  y_start = sides[1]/2
else:
  y_start = -sides[1]/2
if p[2]>0:
  z_start = sides[2]/2
else:
  z_start = -sides[2]/2

dirn = p-p1
dirn
for i in np.arange(x_inters):
  t = (x_start - p1[0])/dirn[0]
  y = p1[1] + t*dirn[1]
  z = p1[2] + t*dirn[2]
  x_walls.append([x_start,y,z])
  x_start = x_start + np.sign(p[0])*sides[0]

for i in np.arange(y_inters):
  t = (y_start - p1[1])/dirn[1]
  x = p1[0] + t*dirn[0]
  z = p1[2] + t*dirn[2]
  y_walls.append([x,y_start,z])
  y_start = y_start + np.sign(p[1])*sides[1]

for i in np.arange(z_inters):
  t = (z_start - p1[2])/dirn[2]
  y = p1[1] + t*dirn[1]
  x = p1[0] + t*dirn[0]
  z_walls.append([x,y,z_start])
  z_start = z_start + np.sign(p[2])*sides[2]

all_inters = np.array(x_walls+y_walls+z_walls)
indexlist =np.argsort(np.linalg.norm(all_inters,axis=1))
all_inters = all_inters[indexlist]
final_coord_out = all_inters                #useful for outside animation
all_inters

array([[ 2.        ,  2.5       ,  2.        ],
       [ 3.33333333,  3.        ,  2.33333333],
       [ 4.        ,  3.25      ,  2.5       ],
       [12.        ,  6.25      ,  4.5       ],
       [18.        ,  8.5       ,  6.        ],
       [19.33333333,  9.        ,  6.33333333],
       [20.        ,  9.25      ,  6.5       ]])

In [ ]:
grid_dim = []
grid_coords = []
final_coords = []
for i in range(len(all_inters)):
  all_inters[i] += np.array(sides)/2
  grid_dim.append([all_inters[i][0]%sides[0] , all_inters[i][1]%sides[1] , all_inters[i][2]%sides[2]])
  grid_coords.append([all_inters[i][0]//sides[0] , all_inters[i][1]//sides[1] , all_inters[i][2]//sides[2]])
  single_final_coord=np.zeros(d)
  for j in range(d):
    if grid_coords[i][j]%2 == 0:
      single_final_coord[j] = (grid_dim[i][j]) - sides[j]/2
    else:
      single_final_coord[j] = sides[j] - (grid_dim[i][j]) - sides[j]/2
  
  final_coords.append(single_final_coord)

final_coords_all.append(final_coords)

In [ ]:
for i in range(len(final_coords_all)):
  for j in range(len(final_coords_all[i])-1,-1,-1):
    if j==len(final_coords_all[i])-1:
      final_coords_all[i].append( np.array(p2) - final_coords_all[i][j])
    if j==0:
      final_coords_all[i][j] -= np.array(p1)
    else:
      final_coords_all[i][j] -=  final_coords_all[i][j-1]

In [ ]:
final_coords_all

[[array([4. , 1.5, 1. ]),
  array([ 1.33333333,  0.5       , -0.33333333]),
  array([ 0.66666667, -0.25      , -0.16666667]),
  array([-8., -3., -2.]),
  array([ 6.  , -2.25, -1.5 ]),
  array([ 1.33333333, -0.5       ,  0.33333333]),
  array([0.66666667, 0.25      , 0.16666667]),
  array([-2.  ,  0.75,  0.5 ])]]

In [ ]:
%%manim cuboid_mirror

class cuboid_mirror(ThreeDScene):
    def construct(self):
      self.set_camera_orientation(phi=80*DEGREES, theta=-60*DEGREES, distance=14)
      self.begin_ambient_camera_rotation()
      cuboid = Prism(dimensions=[sides[0], sides[1], sides[2]]).set_fill(BLUE, opacity=0.2)

      dot = Sphere(center=np.array([p1[0], p1[1], p1[2]]) , color=BLUE, radius=0.08)
      d6  = Sphere(center=np.array([p2[0], p2[1], p2[2]]) , color=BLUE, radius=0.08)
      
      
      def update_path(path):
            previous_path = path.copy()
            previous_path.add_points_as_corners([dot.get_center()])
            path.become(previous_path)
      
      self.add(cuboid)
      self.wait()
      self.add(dot,d6)
      self.wait()
      
      #self.move_camera(0.8*np.pi/2, -0.45*np.pi)


      #for i in range(2): 
      for i in range(len(final_coords_all)):
        dot = Sphere(center=np.array([p1[0], p1[1], p1[2]]) , color=BLUE, radius=0.08)

        path = VMobject()     
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        path.add_updater(update_path)
        
        self.add(path, dot)
        dot.generate_target()
        for j in range(len(final_coords_all[i])):
          dot.target.shift(final_coords_all[i][j][0]*RIGHT , final_coords_all[i][j][1]*UP , final_coords_all[i][j][2]*OUT)
          self.play(MoveToTarget(dot))

        self.play(FadeOut(dot,path))
        self.remove(dot,path)


[07/11/22 07:19:09] INFO     Animation 0 : Partial movie file        ]8;id=279878;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=37573;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/683230426_3002084265_3899514039.m                         
                             p4'                                                             

[07/11/22 07:19:49] INFO     Animation 1 : Partial movie file        ]8;id=103760;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=519495;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/804985698_627190407_2393320559.mp                         
                             4'                                                              

[07/11/22 07:20:47] INFO     Animation 2 : Partial movie file        ]8;id=321493;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=96280;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/3441822456_3952041207_3294177908.                         
                             mp4'                                                            

[07/11/22 07:21:45] INFO     Animation 3 : Partial movie file        ]8;id=490142;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=249363;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/2040023997_1869922644_3222338965.                         
                             mp4'                                                            

[07/11/22 07:22:42] INFO     Animation 4 : Partial movie file        ]8;id=61197;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=722597;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/3351813578_866980217_114818472.mp                         
                             4'                                                              

[07/11/22 07:23:41] INFO     Animation 5 : Partial movie file        ]8;id=37320;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=990219;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/1696842269_4071735628_511260918.m                         
                             p4'                                                             

[07/11/22 07:24:40] INFO     Animation 6 : Partial movie file        ]8;id=966849;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=688410;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/3860794001_1425845550_1327730497.                         
                             mp4'                                                            

[07/11/22 07:25:37] INFO     Animation 7 : Partial movie file        ]8;id=411204;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=709531;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/150061681_487519274_1017016137.mp                         
                             4'                                                              

[07/11/22 07:26:36] INFO     Animation 8 : Partial movie file        ]8;id=773380;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=984203;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/3736070339_1015808967_1635511394.                         
                             mp4'                                                            

[07/11/22 07:27:33] INFO     Animation 9 : Partial movie file        ]8;id=670805;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=754985;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/1719772442_1632440853_1921783309.                         
                             mp4'                                                            

[07/11/22 07:28:32] INFO     Animation 10 : Partial movie file       ]8;id=823190;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=7171;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/cuboid_m                         
                             irror/630306755_1107867685_2443084831.m                         
                             p4'                                                             

                    INFO     Combining to Movie file.                ]8;id=883002;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=569876;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#597\597]8;;\

                    INFO                                             ]8;id=409863;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=406119;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#718\718]8;;\
                             File ready at '/content/media/videos/co                         
                             ntent/1080p60/cuboid_mirror.mp4'                                
                                                                                             

                    INFO     Rendered cuboid_mirror                              ]8;id=510542;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene.py\scene.py]8;;\:]8;id=479986;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene.py#241\241]8;;\
                             Played 11 animations                                            

In [ ]:
%%manim three_d_explanation
class three_d_explanation(ThreeDScene):
    def construct(self):
      self.set_camera_orientation(phi=80*DEGREES, theta=-60*DEGREES, distance=20)
      self.begin_ambient_camera_rotation()
      scale = 10

      cuboid = Prism(dimensions=[sides[0], sides[1], sides[2]]).set_fill(BLUE, opacity=0.2)

      dot = Sphere(center=np.array([p1[0], p1[1], p1[2]])/scale , color=BLUE, radius=0.08)
      d6  = Sphere(center=np.array([p2[0], p2[1], p2[2]])/scale , color=BLUE, radius=0.08)
      
      all_rects_vgroup = VGroup()
       
      for i in np.arange(-3*sides[0]/scale ,3*sides[0]/scale+0.1 , sides[0]/scale):
        row_rects = VGroup()
        for j in np.arange(-3*sides[1]/scale ,3*sides[1]/scale+0.1 , sides[1]/scale):
          col_rects = VGroup()
          for k in np.arange(-3*sides[2]/scale ,3*sides[2]/scale+0.1 , sides[2]/scale):
            new_cuboid = Prism(dimensions=np.array([sides[0], sides[1], sides[2]])/scale).set_fill(BLUE, opacity=0.1)
            new_cuboid.shift(i*RIGHT,j*UP,k*OUT)
            new_cuboid.set_stroke(color=WHITE, width=0.4)

            col_rects.add(new_cuboid)
          row_rects.add(col_rects)
        all_rects_vgroup.add(row_rects)
      
      self.add(dot,d6)
      self.wait()
      self.add(all_rects_vgroup[3][3][3])
      self.wait()
      self.add(all_rects_vgroup)
      all_rects_vgroup[3][3][3].set_fill(PINK, opacity=1)

      arrow_labs = list(itertools.product([2, -2], repeat=d))
      all_arrows = VGroup()
      for i in arrow_labs:
        all_arrows.add(Vector(direction=np.array([i[0]*sides[0]/scale, i[1]*sides[1]/scale, i[2]*sides[2]/scale]),
                              buff=0,
                              color=RED))
      self.play(FadeIn(all_arrows))
      
      signs = list(itertools.product([1, -1], repeat=d))
      box_labels = [(i + np.array([3,3,3])) for i in list(itertools.product([2, -2], repeat=d))]    
      for i in range(len(box_labels)):
        all_rects_vgroup[box_labels[i][0]][box_labels[i][1]][box_labels[i][2]].set_fill(RED, opacity=1)
      self.wait()
      for i in range(len(box_labels)):
        all_rects_vgroup[box_labels[i][0] + signs[i][0]][box_labels[i][1]][box_labels[i][2]].set_fill(YELLOW, opacity=0.5)
        all_rects_vgroup[box_labels[i][0]][box_labels[i][1] + signs[i][1]][box_labels[i][2]].set_fill(YELLOW, opacity=0.5)
        all_rects_vgroup[box_labels[i][0]][box_labels[i][1]][box_labels[i][2] + signs[i][2]].set_fill(YELLOW, opacity=0.5)


      



[07/11/22 07:29:13] INFO     Animation 0 : Partial movie file        ]8;id=402594;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=396626;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/three_d_                         
                             explanation/683230426_3002084265_117847                         
                             3962.mp4'                                                       

[07/11/22 07:29:50] INFO     Animation 1 : Partial movie file        ]8;id=66478;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=542425;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/three_d_                         
                             explanation/804985698_1949745373_624281                         
                             626.mp4'                                                        

[07/11/22 07:32:46] INFO     Animation 2 : Partial movie file        ]8;id=795729;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=153039;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/three_d_                         
                             explanation/3441822456_3267695122_25737                         
                             66985.mp4'                                                      

[07/11/22 07:35:45] INFO     Animation 3 : Partial movie file        ]8;id=316313;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=920833;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#506\506]8;;\
                             written in '/content/media/videos/conte                         
                             nt/1080p60/partial_movie_files/three_d_                         
                             explanation/2040023997_627190407_300991                         
                             3990.mp4'                                                       

                    INFO     Combining to Movie file.                ]8;id=94191;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=73135;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#597\597]8;;\

[07/11/22 07:35:46] INFO                                             ]8;id=72060;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=723747;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene_file_writer.py#718\718]8;;\
                             File ready at '/content/media/videos/co                         
                             ntent/1080p60/three_d_explanation.mp4'                          
                                                                                             

                    INFO     Rendered three_d_explanation                        ]8;id=130590;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene.py\scene.py]8;;\:]8;id=820829;file:///usr/local/lib/python3.7/dist-packages/manim/scene/scene.py#241\241]8;;\
                             Played 4 animations                                             

In [ ]:
signs  = list(itertools.product([1, -1], repeat=d))

box_labels = [(i + np.array([3,3,3])) for i in list(itertools.product([4, -4], repeat=d))]
print(signs)
print(box_labels)

[(1, 1, 1), (1, 1, -1), (1, -1, 1), (1, -1, -1), (-1, 1, 1), (-1, 1, -1), (-1, -1, 1), (-1, -1, -1)]
[array([7, 7, 7]), array([ 7,  7, -1]), array([ 7, -1,  7]), array([ 7, -1, -1]), array([-1,  7,  7]), array([-1,  7, -1]), array([-1, -1,  7]), array([-1, -1, -1])]
